steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Cloning repository..."
        git clone --single-branch --branch "$_BRANCH" "$_TARGET_REPO" app
        chmod -R 755 app  # Secure permissions

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running TruffleHog scan..."
        docker run --rm -v "$(pwd)/app:/pwd" trufflesecurity/trufflehog:3.88.1 git file:///pwd --json --no-update --branch="$_BRANCH" > trufflehog-results.json
        echo $? > trufflehog_exit_code.txt

  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Evaluating TruffleHog scan results..."
        EXIT_CODE=$(cat trufflehog_exit_code.txt)

        if [ "$EXIT_CODE" == "183" ]; then
          echo "TruffleHog detected secrets. Failing the job."
          exit 1
        fi

        if [ ! -s trufflehog-results.json ]; then
          echo "No secrets found. Skipping API upload."
          exit 0
        fi

        echo "Uploading report to CSPM panel..."
        RESPONSE=$(curl --location --request POST "https://${_CSPM_URL}/api/v1/artifact/?tenant_id=${_TENANT_ID}&data_type=TruffleHog&save_to_s3=true&label_id=${_LABEL}" \
          --header "Tenant-Id: ${_TENANT_ID}" \
          --header "Authorization: Bearer ${_AK_TOKEN}" \
          --form "file=@$(pwd)/trufflehog-results.json")
        echo "Response: $RESPONSE"

        if [[ "$RESPONSE" != *"File received successfully"* ]]; then
          echo "Error: Failed to upload report to CSPM panel"
          exit 1
        fi

substitutions:
  _CSPM_URL: "cspm.demo.accuknox.com"
  _TENANT_ID: "3730"
  _LABEL: "GCPSECRETSCAN"
  _TARGET_REPO: "https://github.com/th3-v3ng34nc3/leaky-repo"
  _BRANCH: "master"
  _AK_TOKEN: "YOUR_SECRET_TOKEN"

artifacts:
  objects:
    location: 'gs://secret-scan-se/'
    paths:
      - 'trufflehog-results.json'

options:
  logging: CLOUD_LOGGING_ONLY
